### ISSUE TITLE
Alternative crystal cross-compiling

### ISSUE THREAD

**Issue by faustinoaq** [mrfoto/slacker#1]
@mrfoto This is an awesome project!

I'm using Raspberry Pi too :+1: 

I know [portalier package](http://public.portalier.com/raspbian/) is a bit outdated, so I use cross-compiling:

> **Requirements:** RPi (`gcc`, `libprce3-dev`, `libevent-dev`, `libssl-dev`) PC (`llvm`)

1. Cross-compile the object file on your dev computer (see output)

> **Note:** Tempfile isn't supported on arm yet, comment these lines on Kemal: (`lib/kemal/src/kemal/file_uploader.cr`)
> (already fixed on crystal/master see: https://github.com/crystal-lang/crystal/pull/5640)

https://github.com/kemalcr/kemal/blob/6fbad555d05bd3ac3735adf7abdca08927cfee25/src/kemal/file_upload.cr#L13-L16

_Also remember to comment `getter tmpfile : Tempfile` at line 4_

```sh
crystal build server.cr --cross-compile --target="arm-unknown-linux-gnueabihf" -s
Parse:                             00:00:00.000236778 (   0.25MB)
Semantic (top level):              00:00:01.272815827 ( 100.45MB)
Semantic (new):                    00:00:00.002450326 ( 100.45MB)
Semantic (type declarations):      00:00:00.037667248 ( 108.45MB)
Semantic (abstract def check):     00:00:00.002489012 ( 108.45MB)
Semantic (ivars initializers):     00:00:00.012113343 ( 108.45MB)
Semantic (cvars initializers):     00:00:00.011383142 ( 108.45MB)
Semantic (main):                   00:00:01.165512252 ( 172.82MB)
Semantic (cleanup):                00:00:00.001283736 ( 172.82MB)
Semantic (recursive struct check): 00:00:00.001738710 ( 172.82MB)
Codegen (crystal):                 00:00:00.589332905 ( 172.82MB)
cc 'server.o' -o 'server'  -rdynamic  -lz `command -v pkg-config > \
/dev/null && pkg-config --libs libssl || \
printf %s '-lssl -lcrypto'` `command -v pkg-config > \
/dev/null && pkg-config --libs libcrypto || \
printf %s '-lcrypto'` -lyaml -lpcre -lm -lgc -lpthread \
/usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib

Macro runs:
 - /usr/lib/crystal/ecr/process.cr: 00:00:00.848106195
```

2. Copy `.o` file to RPi

3. Create `libcrystal.a` on RPi (linker dependency)

```sh
git clone https://github.com/crystal-lang/crystal.git
cd crystal
make deps # just build libcrystal.a for arm-unknown-linux-gnueabihf architecture
```

Then check `~/crystal/src/ext/libcrystal.a` has been created :tada: 

4. Create an executable using cross-compiling output (1)

```
cc 'server.o' -o 'server'  -rdynamic  -lz `command -v pkg-config > \
/dev/null && pkg-config --libs libssl || \
printf %s '-lssl -lcrypto'` `command -v pkg-config > \
/dev/null && pkg-config --libs libcrypto || \
printf %s '-lcrypto'` -lyaml -lpcre -lm -lgc -lpthread \
/home/pi/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib
```

> **Note:** we changed `/usr/lib/crystal/ext/libcrystal.a` by `/home/pi/crystal/src/ext/libcrystal.a`_

And that's all, if you follow these steps you should be able to cross compile your project successfully to RPi

> **Note:** This process looks a bit complex but is very useful if you don't want to install crystal in your RPi because memory, space requirements and so on.

### Static compiled binary

I compiled master https://github.com/mrfoto/slacker/commit/f4baf71661bf7c1c87785db37c1e4469e5566f36 statically adding `-static` flag to linker command (see step 4) 

> **Note:** `public/` folder isn't included on static executable, so this directory is still required

```sh
$ file server
server: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked,
for GNU/Linux 3.2.0, BuildID[sha1]=e1d8796d9ecdb18ab087deaa2e8977eed9acc620, not stripped
$ sha256sum server
7a31e7ee48644fb31596f9682c022450d404cc753e8548cd7864ac472ccb3d05  server
$ ldd server
        not a dynamic executable
```

Try it! [server.tar.gz](https://github.com/mrfoto/slacker/files/1822223/server.tar.gz) 

:tada:

**Comment by faustinoaq** [comment]
Documentation here; https://crystal-lang.org/docs/syntax_and_semantics/cross-compilation.html

**Comment by miharekar** [comment]
Well this might be simple for you, but it goes *way* over my head 😅 
In the meantime @ysbaddaden updated packages on portalier.com and also added `0.24.2-3` with the Tempfile patch so it compiles just fine without patching Kemal 🎉️

**Comment by elorest** [comment]
Great writeup @faustinoaq. Miss working with you.
